"""Agregar campos de notas y modalidad a Turno

Revision ID: 6d6d31f3e474
Revises: 5f61b7eee03a
Create Date: 2025-11-14 16:04:28.703780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6d31f3e474'
down_revision = '5f61b7eee03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notas_doctor', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_column('notas_doctor')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('modalidad')

    # ### end Alembic commands ###
